.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.TH MSTPCTL 8 "April 29, 2013" "" ""
.SH NAME
mstpctl \- STP/RSTP/MSTP configuration
.SH SYNOPSIS
.BR "mstpctl [command]"
.SH DESCRIPTION
.B mstpctl
is used to configure Spanning Tree and Rapid Spanning Tree
configuration. Multiple Spanning Tree configuration is not supported
currently. MSTPCTL is used for configuring STP parameters on bridges
which have STP enabled. Currently, STP is disabled by default on the bridge.
To enable STP, configure "brctl stp <bridge> on".

.SH SPANNING TREE PROTOCOL CONFIGURATION

.IR mstpctl(8)
can be used for configuring certain spanning tree protocol
parameters. For an explanation of these parameters, see the IEEE
802.1D and 802.1Q specification .

.B mstpctl setmaxage <bridge> <max_age>
sets the bridge's 'maximum age' to <time> seconds.

.B mstpctl setfdelay <bridge> <time>
sets the bridge's 'bridge forward delay' to <time> seconds.

.B mstpctl setmaxhops <bridge> <max_hops>
sets the bridge's 'maximum hops' to <max_hops>.

.B mstpctl setforcevers <bridge> {mstp|rstp|stp}
sets the bridge's force STP version to either rstp/stp. mstp is
not supported currently.

.B mstpctl settxholdcount <bridge> <tx_hold_count>
sets the bridge's 'bridge transmit hold count' to <tx_hold_count>.

.B mstpctl settreeprio <bridge> <mstid> <priority>
sets the bridge tree priority to <priority> for an MSTI instance.
Only mstid value 0 is supported currently. The priority value is a number
between 0 and 65535 and is a multiple of 4096. The bridge with the lowest
priority will be elected 'root bridge'.

.B mstpctl setportpathcost <bridge> <port> <cost>
sets the port cost of the port <port> in bridge <bridge> to <cost>.

.B mstpctl setportadminedge <bridge> <port> {yes|no}
Enables/disables the initial edge state of the port <port> in bridge <bridge>.

.B mstpctl setportautoedge <bridge> <port> {yes|no}
Enables/disables the auto transition to/from edge state of the port <port> in
bridge <bridge>.

.B mstpctl setportp2p <bridge> <port> {yes|no|auto}
Enables/disables the point2point detection mode of the port <port> in
bridge <bridge>.

.B mstpctl setportrestrrole <bridge> <port> {yes|no}
Enables/disables the port ability to take root role of the port <port> in
bridge <bridge>.

.B mstpctl setportrestrtcn <bridge> <port> {yes|no}
Enables/disables the port ability to propagate received topology change
notification of the port <port> in bridge <bridge>.

.B mstpctl setbpduguard <bridge> <port> {yes|no}
Enables/disables the bpduguard configuration of the port in bridge <bridge>.

.B mstpctl settreeportprio <bridge> <port> <mstid> <priority>
sets the port <port>'s priority to <priority> for the MSTI instance.
The priority value is a number between 0 and 240 and is a multiple of 16.

.B mstpctl sethello <bridge> <time>
sets the bridge's 'bridge hello time' to <time> seconds.

.B mstpctl setageing <brname> <time>
sets the ethernet (MAC) address ageing time, in seconds for the bridge
when the running version is STP, but not RSTP/MSTP.

.B mstpctl setportnetwork <bridge> <port> {yes|no}
Enables/disables the bridge assurance capability for a network port <port> in
bridge <bridge>.

.SH SPANNING TREE PROTOCOL SHOW COMMANDS
.B mstpctl showbridge <brname>
will show information of the bridge.

.B mstpctl showport <brname>
will show information of the bridge ports.

.B mstpctl showportdetail <brname>
will show detailed information of the bridge ports.

.B mstpctl showtree <brname> <mstid>
will show tree information of the bridge in MSTI instance.

.B mstpctl showtreeport <brname> <port> <mstid>
will show per tree port information of the bridge port in MSTI instance.

.B mstpctl showall
will show detailed information of the bridge.

.SH SEE ALSO
.BR brctl(8)

.SH AUTHOR
The source code for mstpctl was written by Vitalii Demianets
<vitas@nppfactor.kiev.ua>. This manpage was written by Satish Ashok
<sashok@cumulusnetworks.com> based on \fBbrctl\fP(8).
